source "https://rubygems.org"

ruby "3.0.2"

gem "artsy-auth"
gem "bootstrap_form"
gem "coderay"
gem "coffee-rails"
gem "dalli"
gem "data_uri"
gem "ddtrace"
gem "faraday", "~> 0.9"
gem "foreman"
gem "google-analytics-rails"
gem "haml-rails"
gem "hiredis"
gem "hyperclient", "~> 0.9.3"
gem "jquery-rails"
gem "nokogiri"
gem "oauth2", "1.4.9"
gem "puma"
gem "rails", "~> 6.1"
gem "redcarpet"
gem "redis-rails"
gem "sass-rails"
gem "sprockets", "< 4.0"
gem "sprockets-rails"
gem "sentry-ruby"
gem "sentry-rails"
gem "twitter-bootstrap-rails"
gem "twitter-bootstrap-rails-confirm"
gem "uglifier"
gem "webrick"

group :development do
  gem "guard"
  gem "guard-bundler"
  gem "guard-coffeescript"
  gem "guard-rspec"
  gem "guard-rubocop"
  gem "spring"
end

group :development, :test do
  gem "byebug"
  gem "capybara"
  gem "rspec-rails"
  gem "standard"
  gem "selenium-webdriver"
end
